### ISSUE TITLE
Fatal Exception: android.os.BadParcelableException

### ISSUE THREAD

**Issue by smer4ik** [dmytrodanylyk/circular-progress-button#84]
After application is removed from memory by system, and I open it again, I receive this crash.

android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.dd.CircularProgressButton$SavedState
       at android.os.Parcel.readParcelableCreator(Parcel.java:2411)
       at android.os.Parcel.readParcelable(Parcel.java:2337)
       at android.os.Parcel.readValue(Parcel.java:2243)
       at android.os.Parcel.readSparseArrayInternal(Parcel.java:2653)
       at android.os.Parcel.readSparseArray(Parcel.java:1946)
       at android.os.Parcel.readValue(Parcel.java:2300)
       at android.os.Parcel.readArrayMapInternal(Parcel.java:2592)
       at android.os.BaseBundle.unparcel(BaseBundle.java:221)
       at android.os.Bundle.getBundle(Bundle.java:763)
       at com.google.android.gms.maps.internal.cv.a(SourceFile:74)
       at com.google.maps.api.android.lib6.d.ft.a()
       at com.google.maps.api.android.lib6.d.ap.a()
       at com.google.android.gms.maps.internal.aa.onTransact(SourceFile:66)
       at android.os.Binder.transact(Binder.java:387)
       at com.google.android.gms.maps.internal.IMapViewDelegate$zza$zza.onCreate()
       at com.google.android.gms.maps.MapView$zza.onCreate()
       at com.google.android.gms.dynamic.zza$3.zzb()
       at com.google.android.gms.dynamic.zza$1.zza()
       at com.google.android.gms.maps.MapView$zzb.zzvu()
       at com.google.android.gms.maps.MapView$zzb.zza()
       at com.google.android.gms.dynamic.zza.zza()
       at com.google.android.gms.dynamic.zza.onCreate()
       at com.google.android.gms.maps.MapView.onCreate()
       at linord.iforge.com.logIn.EnterMobileFragment.onCreateView(EnterMobileFragment.java:74)
       at android.support.v4.app.Fragment.performCreateView(Fragment.java:1789)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:955)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
       at android.support.v4.app.BackStackRecord.popFromBackStack(BackStackRecord.java:960)
       at android.support.v4.app.FragmentManagerImpl.popBackStackState(FragmentManager.java:1553)
       at android.support.v4.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:506)
       at android.support.v4.app.FragmentActivity.onBackPressed(FragmentActivity.java:178)
       at android.app.Activity.onKeyUp(Activity.java:2424)
       at android.view.KeyEvent.dispatch(KeyEvent.java:2654)
       at android.app.Activity.dispatchKeyEvent(Activity.java:2675)
       at com.android.internal.policy.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2299)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4078)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4040)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3593)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3646)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3612)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3738)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3620)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3795)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3593)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3646)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3612)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3620)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3593)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3646)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3612)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3771)
       at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:3932)
       at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2221)
       at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1843)
       at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1834)
       at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2198)
       at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:323)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5401)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:725)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:615)

**Comment by dmytrodanylyk** [comment]
Hi, this library soon will be depricated. I am currently working on a new library - *Morphing Button*. This library should be more generic and easier to use. So, sorry but currently I don't have time to fix `circular-progress-button`. Hope u will enjoy using new library, which will ofc has all features of `circular-progress-button`.

**Comment by mindrunner** [comment]
Same problem here. And it actually seems to be a general problem in using third party libraries. Most of them are not maintained anymore and we have to fix bugs by our own. Looks like this is the next library I have to migrate from :(

**Comment by dmytrodanylyk** [comment]
```
This library is not more supported. 
If you want to add new feature or fix a bug, grab source code and do it. If you think your
fix or feature would be useful to other developers, I can add link of your repository to
this README file. Use following e-mail to contact me: dmytrodanylyk@gmail.com
Thank you for using my libraries.
```

**Note:** updated version of this library will be available [here](https://github.com/dmytrodanylyk/android-morphing-button).
